### ISSUE TITLE
https://fakerql.com/ is done

### ISSUE THREAD

**Issue by eskan** [notrab/fakerql#50]
Hi,
is the website is closed forever ?
Cheers,

**Comment by MartinN3** [comment]
i cant imagine cost of such a server 🗡  honestly i recommend to run server localy, its quite easy

**Comment by eskan** [comment]
Its interesting to have a such server with cors to demonstrate graphql in website like stackblitz. So the question is asked to the maintener is it waned or not ? and eventually is someone know an alternative to it ? if yes may be it should be referenced here.
fakerql is pretty useful ...

**Comment by notrab** [comment]
Hey @eskan @MartinN3 

Thanks for bringing this to my attention. I'll get it fixed and deployed over the next few days 👍

**Comment by notrab** [comment]
Update: For some reason Now will not deploy this at all, and the errors are non existent which is really really odd. Hang in there!

**Comment by lukasbalaz** [comment]
Any update on this ?

**Comment by notrab** [comment]
Hi @lukasbalaz 

I'm working on updating this repo to Yoga2 + Nexus. I've reached out to Zeit about why this will no longer deploy but no resolution yet.

**Comment by notrab** [comment]
Update: Half way through the rewrite.

**Comment by notrab** [comment]
It's back online now https://fakerql.com 🚀

**Comment by mxmlnglt** [comment]
Hello @notrab this happened again: 404 error now.

**Comment by ptahdunbar** [comment]
Hey @notrab - I'm getting 404s on https://fakerql.com
